Navbar and User Table
JatinJainSaraf/product-catalog pull request #47
Opened 2024-02-19 05:11 UTC by wdcs-harshitshah

2024-02-21 06:39 UTC, wdcs-jatinjain commented on admin/public/logo.svg
Add more visible logo on brighter UI

2024-02-23 11:41 UTC, JatinJainSaraf commented on admin/src/app/api/users/delete-user/[userId]/route.ts
> +export async function DELETE(req: Request, {params}: any) {
any

2024-02-23 12:50 UTC, JatinJainSaraf reviewed
Reviewed Admin CHanges please resolve the conversation once you push the changes

2024-02-23 12:50 UTC, JatinJainSaraf commented on admin/src/app/api/users/edit-user/[userId]/route.ts
> +export async function PATCH(req: Request,  {params}: any) {
user proper types for params

2024-02-23 12:50 UTC, JatinJainSaraf commented on admin/src/app/api/users/get-user/[userId]/route.ts
> +export async function GET(req: Request,{params}:any ) {
user proper types for params

2024-02-23 12:50 UTC, JatinJainSaraf commented on admin/src/app/components/EditUserComponent/index.tsx
delete this un used component

2024-02-23 12:50 UTC, JatinJainSaraf commented on admin/public/logo.svg
use big icon and align it with nav items

2024-02-23 12:50 UTC, JatinJainSaraf commented on admin/src/app/(home)/users/edit-user/[userId]/page.tsx
> +const EditSingleUserPage = ({params}:{params:{userId:string}}) => {
EditSingleUserPage rename this to EditUserPage

2024-02-23 12:50 UTC, JatinJainSaraf commented on admin/src/app/(home)/users/get-user/[userId]/page.tsx
delete this unused route

2024-02-23 12:50 UTC, JatinJainSaraf commented on admin/src/app/api/users/add-user/route.ts
> +import { API_URL } from "../../../../../config";
use import alias instead of ../../../../../../.././/../..//

2024-02-23 12:50 UTC, JatinJainSaraf commented on admin/src/app/api/users/add-user/route.ts
> +    console.log(name, email, role, phone,postalCode,streetAddress,city,country, API_URL);
remove console

2024-02-23 12:50 UTC, JatinJainSaraf commented on admin/src/app/api/users/add-user/route.ts
> +    const UserAddedReturnData = await AddedUserResponse.json();
add proper type for UserAddedReturnData

2024-02-23 12:50 UTC, JatinJainSaraf commented on admin/src/app/api/users/delete-user/[userId]/route.ts
> +  console.log(req)
remove console

2024-02-23 12:50 UTC, JatinJainSaraf commented on admin/src/app/api/users/delete-user/[userId]/route.ts
> +    const UserDeletedReturnData = await DeletededUserResponse.json();
add proper type for UserDeletedReturnData

2024-02-23 12:50 UTC, JatinJainSaraf commented on admin/src/app/api/users/edit-user/[userId]/route.ts
> +  const { name, email, role } = await req.json();
if the add user has 7-8 fields then why does the edit user have 3 fields. do you not intend to update the rest of the fields?
please update this

2024-02-23 12:50 UTC, JatinJainSaraf commented on admin/src/app/api/users/edit-user/[userId]/route.ts
> +    const UserEditedReturnData = await EditededUserResponse.json();
add proper types for UserEditedReturnData

2024-02-23 12:50 UTC, JatinJainSaraf commented on admin/src/app/components/Users/Add-User/index.tsx
> +  const onAddingUser = async (a:any) => {
what sense does a variable name make here with any type?

rename this and use the proper type in it.

don't forget we are using type script

2024-02-23 12:50 UTC, JatinJainSaraf commented on admin/src/app/components/Users/Add-User/index.tsx
> +      const AddUserResponse: any = await response.json();
use proper type for AddUserResponse

2024-02-23 12:50 UTC, JatinJainSaraf commented on admin/src/app/components/Users/Edit-User/index.tsx
> +const onEditingUser = async (a:any) => {
user proper variables names with proper types

2024-02-23 12:50 UTC, JatinJainSaraf commented on admin/src/app/components/Users/Edit-User/index.tsx
> +    const EditUserResponse: any = await response.json();
use proper types

2024-02-23 12:50 UTC, JatinJainSaraf commented on admin/src/app/components/Users/Edit-User/index.tsx
> +      console.log("🚀 ~ fetchUserDetails ~ GetAllUsersReturnData:", GetSingleUsersReturnData)
remove cosole

2024-02-23 12:50 UTC, JatinJainSaraf commented on admin/src/app/components/Users/Edit-User/index.tsx
> +      {setUserDetails(GetSingleUsersReturnData.data);}
if user is updated successfull are you not redirecting it to user list ?

2024-02-23 12:50 UTC, JatinJainSaraf commented on admin/src/app/components/Users/index.tsx
> +      const userDeleteResponse = await response.json();
use proper type for userDeleteResponse

2024-02-23 13:21 UTC, JatinJainSaraf requested changes

2024-02-23 13:21 UTC, JatinJainSaraf commented on server/src/controllers/admin/users/addUser.ts
> +    console.log(AddedUser)
remove console

2024-02-23 13:21 UTC, JatinJainSaraf commented on server/src/controllers/admin/users/addUser.ts
> +    const AddedUser = await Views.UserViews.createUserViews( { email, name, role, streetAddress,postalCode,city, country, phone,password})
variable name should be in camel case

addedUser sounds weird rename it to addUserViewsRes

2024-02-23 13:21 UTC, JatinJainSaraf commented on server/src/controllers/admin/users/addUser.ts
> +    const AddedUser = await Views.UserViews.createUserViews( { email, name, role, streetAddress,postalCode,city, country, phone,password})
AddedUser should have proper type

2024-02-23 13:21 UTC, JatinJainSaraf commented on server/src/controllers/admin/users/checkAdminLogin.ts
> +    const isLoggedUser = await Views.UserViews.checkAdminLoginViews({
isLoggedUser rename it to checkAdminLoginViewsRes

2024-02-23 13:21 UTC, JatinJainSaraf commented on server/src/controllers/admin/users/checkAdminLogin.ts
> +    const isLoggedUser = await Views.UserViews.checkAdminLoginViews({
please add type for the variable

2024-02-23 13:21 UTC, JatinJainSaraf commented on server/src/controllers/admin/users/deleteUser.ts
> +  const id: string = req.query.id as string;
destructure id from query in delete user params itself

2024-02-23 13:21 UTC, JatinJainSaraf commented on server/src/controllers/admin/users/deleteUser.ts
> +    return res.status(200).json(deletedUser);
rename deletedUser with removeUserViewsRes

2024-02-23 13:21 UTC, JatinJainSaraf commented on server/src/controllers/admin/users/deleteUser.ts
> +    return res.status(200).json(deletedUser);
if there is someting returned from removeUserViews  then please assign proper type for variable in which you are storing it

2024-02-23 13:21 UTC, JatinJainSaraf commented on server/src/controllers/admin/users/editSingleUser.ts
> +    body: { name, email, role },
user have mnay fields but here you are using only 3 Why?

2024-02-23 13:21 UTC, JatinJainSaraf commented on server/src/controllers/admin/users/editSingleUser.ts
> +  }: { body: { name: string; email: string; role: string }; query: any },
use proper types

2024-02-23 13:21 UTC, JatinJainSaraf commented on server/src/controllers/admin/users/editSingleUser.ts
> +  const id: any = query.id;
use proper types rather than any

2024-02-26 08:52 UTC, JatinJainSaraf commented on admin/src/app/api/login/route.ts
> +    const UserLoginReturnData = await UserLoginResponse.json();
Use proper type for UserLoginReturnData

2024-02-26 09:00 UTC, JatinJainSaraf commented on admin/src/app/components/Api-Logs/index.tsx
> +        <PageHeader pageTitle='APILogsPage' showAddButton={true} addRouter={'/users/api-log'} />
we dont need add button on api logs

2024-02-26 09:01 UTC, JatinJainSaraf commented on admin/src/app/components/CustomerComponent/index.tsx
> +      <div className="m-3 justify-between"></div>
admin can not add customer (end user ) from admin panel

2024-02-26 10:19 UTC, JatinJainSaraf requested changes

2024-02-26 10:19 UTC, JatinJainSaraf commented on server/src/controllers/admin/users/getAllUsers.ts
> +    console.log("🚀 ~ getAllUsers ~ fetchAllUsers:", fetchAllUsers)
remove console

2024-02-26 10:19 UTC, JatinJainSaraf commented on server/src/controllers/admin/users/getUser.ts
> +
It's a 'get user' API that only requires an ID from the query to fetch user details corresponding to that ID. Therefore, there is no need to pass a request or body.

2024-02-26 10:19 UTC, JatinJainSaraf commented on server/src/controllers/admin/users/getUser.ts
> +      { email, name, role,password, phone, city, country, streetAddress, postalCode, id}
no need to pass this in views

2024-02-26 10:21 UTC, JatinJainSaraf commented on server/src/views/admin/user/deletedUser.ts
> +        },
follow sentence case in error messages

2024-02-26 10:22 UTC, JatinJainSaraf commented on server/src/views/admin/user/deletedUser.ts
> +      };
follow sentence case in error messages

2024-02-26 10:22 UTC, JatinJainSaraf commented on server/src/views/admin/user/deletedUser.ts
> +      };
follow sentence case in  messages

2024-02-26 10:22 UTC, JatinJainSaraf commented on server/src/views/admin/user/deletedUser.ts
> +    console.error("An error occurred while Deleting the User :", error);
follow sentence case in  messages

2024-02-26 10:23 UTC, JatinJainSaraf commented on server/src/views/admin/user/editUser.ts
> +        message: "Cannot Edit Email Id"
please use proper message

2024-02-26 10:24 UTC, JatinJainSaraf commented on server/src/views/admin/user/editUser.ts
> +        message: "Something Went Wrong",
user sentence case for message

2024-02-26 10:25 UTC, JatinJainSaraf commented on server/src/views/admin/user/editUser.ts
> +      message: "User updated successfully",
user sentence case for message

2024-02-27 08:47 UTC, JatinJainSaraf approved these changes

2024-02-27 08:48 UTC, merged